---
- name: variable demo
  hosts: host2
  become: yes
  vars: 
    myusernmae: cleopatra

  tasks:
  - name: update static page
    copy:
      src: static.html
      dest: /var/www/html/static.html   
...