---
- name: variable demo
  hosts: host1
  become: yes
  vars: 
    myusernmae: cleopatra

  tasks:
  - name: update static page
    copy:
      src: dynamic.j2
      dest: /var/www/html/static.html   
...